server:
  port: 9000
  tomcat:
    basedir: F:\springboot-tomcat-tmp

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fangguansuo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

