package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Buildinginfo;
import com.woniu.housemanager.pojo.BuildinginfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildinginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(BuildinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(BuildinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(Buildinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(Buildinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<Buildinginfo> selectByExample(BuildinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    Buildinginfo selectByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Buildinginfo record, @Param("example") BuildinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") Buildinginfo record, @Param("example") BuildinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(Buildinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(Buildinginfo record);

    Integer selectByid(String projectname);
}