package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Bunessreview;
import com.woniu.housemanager.pojo.BunessreviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BunessreviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(BunessreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(BunessreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer auditid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(Bunessreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(Bunessreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<Bunessreview> selectByExample(BunessreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    Bunessreview selectByPrimaryKey(Integer auditid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bunessreview record, @Param("example") BunessreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") Bunessreview record, @Param("example") BunessreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(Bunessreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessreview
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(Bunessreview record);
}