package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Bunessdetials;
import com.woniu.housemanager.pojo.BunessdetialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

public interface BunessdetialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(BunessdetialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(BunessdetialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer bdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(Bunessdetials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(Bunessdetials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<Bunessdetials> selectByExample(BunessdetialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    Bunessdetials selectByPrimaryKey(Integer bdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bunessdetials record, @Param("example") BunessdetialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") Bunessdetials record, @Param("example") BunessdetialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(Bunessdetials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bunessdetials
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(Bunessdetials record);
    //所有的他项权名
    List findAllMortgages(Integer btid);
    //他项权需要的资料
    List findAllMaterials(String bdname);
}