package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Bussnessstatus;
import com.woniu.housemanager.pojo.BussnessstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BussnessstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int countByExample(BussnessstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int deleteByExample(BussnessstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int deleteByPrimaryKey(String bsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int insert(Bussnessstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int insertSelective(Bussnessstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    List<Bussnessstatus> selectByExample(BussnessstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    Bussnessstatus selectByPrimaryKey(String bsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int updateByExampleSelective(@Param("record") Bussnessstatus record, @Param("example") BussnessstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int updateByExample(@Param("record") Bussnessstatus record, @Param("example") BussnessstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int updateByPrimaryKeySelective(Bussnessstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussnessstatus
     *
<<<<<<< HEAD
     * @mbggenerated Thu Jun 11 20:24:34 CST 2020
=======
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
>>>>>>> 0fc7e1b36801db5f83f76ff31aeb5386253e1e95
     */
    int updateByPrimaryKey(Bussnessstatus record);

    List ybdydjfindAll(String acard);

    List ybdyzydjfindAll(String acard);

    List ybdybgdjfindAll(String acard);

    List ybdyzxdjfindAll(String acard);
}