package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Debt;
import com.woniu.housemanager.pojo.DebtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DebtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(DebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(DebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer debt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<Debt> selectByExample(DebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    Debt selectByPrimaryKey(Integer debt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Debt record, @Param("example") DebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") Debt record, @Param("example") DebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(Debt record);
}