package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Devision;
import com.woniu.housemanager.pojo.DevisionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(DevisionExample example);

    List findByAreaId(Integer areaId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(DevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer devisionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(Devision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(Devision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<Devision> selectByExample(DevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    Devision selectByPrimaryKey(Integer devisionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Devision record, @Param("example") DevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") Devision record, @Param("example") DevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(Devision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(Devision record);

    List findAllByarename(Integer areaid);
}