package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.GetPeople;
import com.woniu.housemanager.pojo.GetPeopleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GetPeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(GetPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(GetPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer gpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(GetPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(GetPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<GetPeople> selectByExample(GetPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    GetPeople selectByPrimaryKey(Integer gpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") GetPeople record, @Param("example") GetPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") GetPeople record, @Param("example") GetPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(GetPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getpeople
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(GetPeople record);
}