package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.HouseProperty;
import com.woniu.housemanager.pojo.HousePropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HousePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(HousePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(HousePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer hpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(HouseProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(HouseProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<HouseProperty> selectByExample(HousePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    HouseProperty selectByPrimaryKey(Integer hpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") HouseProperty record, @Param("example") HousePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") HouseProperty record, @Param("example") HousePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(HouseProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houseproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(HouseProperty record);
}