package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.HouseTransfer;
import com.woniu.housemanager.pojo.HouseTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(HouseTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(HouseTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer housetransferid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(HouseTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(HouseTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<HouseTransfer> selectByExample(HouseTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    HouseTransfer selectByPrimaryKey(Integer housetransferid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") HouseTransfer record, @Param("example") HouseTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") HouseTransfer record, @Param("example") HouseTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(HouseTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housetransfer
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(HouseTransfer record);
}