package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.KaiFaShang;
import com.woniu.housemanager.pojo.KaiFaShangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KaiFaShangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(KaiFaShangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(KaiFaShangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer diid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(KaiFaShang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(KaiFaShang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<KaiFaShang> selectByExample(KaiFaShangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    KaiFaShang selectByPrimaryKey(Integer diid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") KaiFaShang record, @Param("example") KaiFaShangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") KaiFaShang record, @Param("example") KaiFaShangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(KaiFaShang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(KaiFaShang record);
}