package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.LandProperty;
import com.woniu.housemanager.pojo.LandPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LandPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int countByExample(LandPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByExample(LandPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int deleteByPrimaryKey(Integer lpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insert(LandProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int insertSelective(LandProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    List<LandProperty> selectByExample(LandPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    LandProperty selectByPrimaryKey(Integer lpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") LandProperty record, @Param("example") LandPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByExample(@Param("record") LandProperty record, @Param("example") LandPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKeySelective(LandProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table landproperty
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    int updateByPrimaryKey(LandProperty record);
}