package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.LouDong;
import com.woniu.housemanager.pojo.LouDongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LouDongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int countByExample(LouDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int deleteByExample(LouDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int deleteByPrimaryKey(Integer loudongid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int insert(LouDong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int insertSelective(LouDong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    List<LouDong> selectByExample(LouDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    LouDong selectByPrimaryKey(Integer loudongid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") LouDong record, @Param("example") LouDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int updateByExample(@Param("record") LouDong record, @Param("example") LouDongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int updateByPrimaryKeySelective(LouDong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loudong
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    int updateByPrimaryKey(LouDong record);
}