package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.MakeWay;
import com.woniu.housemanager.pojo.MakeWayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MakeWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(MakeWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(MakeWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer mwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(MakeWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(MakeWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<MakeWay> selectByExample(MakeWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    MakeWay selectByPrimaryKey(Integer mwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") MakeWay record, @Param("example") MakeWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") MakeWay record, @Param("example") MakeWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(MakeWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(MakeWay record);
}