package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.materials;
import com.woniu.housemanager.pojo.materialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface materialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(materialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(materialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<materials> selectByExample(materialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    materials selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") materials record, @Param("example") materialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") materials record, @Param("example") materialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(materials record);
}