package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.MortgagesLogout;
import com.woniu.housemanager.pojo.MortgagesLogoutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MortgagesLogoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int countByExample(MortgagesLogoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int deleteByExample(MortgagesLogoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int deleteByPrimaryKey(Integer mlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int insert(MortgagesLogout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int insertSelective(MortgagesLogout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    List<MortgagesLogout> selectByExample(MortgagesLogoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    MortgagesLogout selectByPrimaryKey(Integer mlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") MortgagesLogout record, @Param("example") MortgagesLogoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int updateByExample(@Param("record") MortgagesLogout record, @Param("example") MortgagesLogoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int updateByPrimaryKeySelective(MortgagesLogout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageslogout
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    int updateByPrimaryKey(MortgagesLogout record);
}