package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.MortgagesChange;
import com.woniu.housemanager.pojo.MortgagesChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MortgagesChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int countByExample(MortgagesChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int deleteByExample(MortgagesChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int deleteByPrimaryKey(Integer mcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int insert(MortgagesChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int insertSelective(MortgagesChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    List<MortgagesChange> selectByExample(MortgagesChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    MortgagesChange selectByPrimaryKey(Integer mcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") MortgagesChange record, @Param("example") MortgagesChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int updateByExample(@Param("record") MortgagesChange record, @Param("example") MortgagesChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int updateByPrimaryKeySelective(MortgagesChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mortgageschange
     *
     * @mbggenerated Wed Jun 17 17:01:35 CST 2020
     */
    int updateByPrimaryKey(MortgagesChange record);
}