package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.PresalePermit;
import com.woniu.housemanager.pojo.PresalePermitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresalePermitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(PresalePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(PresalePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer pspid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(PresalePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(PresalePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<PresalePermit> selectByExample(PresalePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    PresalePermit selectByPrimaryKey(Integer pspid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") PresalePermit record, @Param("example") PresalePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") PresalePermit record, @Param("example") PresalePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(PresalePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presalepermit
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(PresalePermit record);
}