package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.RoleTree;
import com.woniu.housemanager.pojo.RoleTreeExample;
import com.woniu.housemanager.pojo.RoleTreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(RoleTreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(RoleTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(RoleTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<RoleTree> selectByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    RoleTree selectByPrimaryKey(RoleTreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleTree record, @Param("example") RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") RoleTree record, @Param("example") RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(RoleTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(RoleTree record);
}