package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.Structrue;
import com.woniu.housemanager.pojo.StructrueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StructrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(StructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(StructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer structureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(Structrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(Structrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<Structrue> selectByExample(StructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    Structrue selectByPrimaryKey(Integer structureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") Structrue record, @Param("example") StructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") Structrue record, @Param("example") StructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(Structrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structrue
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(Structrue record);
}