package com.woniu.housemanager.mapper;

import com.woniu.housemanager.pojo.WorkerInfo;
import com.woniu.housemanager.pojo.WorkerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int countByExample(WorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByExample(WorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer workid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insert(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int insertSelective(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    List<WorkerInfo> selectByExample(WorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    WorkerInfo selectByPrimaryKey(Integer workid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") WorkerInfo record, @Param("example") WorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") WorkerInfo record, @Param("example") WorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workerinfo
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    int updateByPrimaryKey(WorkerInfo record);
}