package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class Applicant implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.aname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.acard
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String acard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.aadress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String aadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.aphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String aphone;

    private Commoninfo commoninfo;

    public Commoninfo getCommoninfo() {
        return commoninfo;
    }

    public void setCommoninfo(Commoninfo commoninfo) {
        this.commoninfo = commoninfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applicant.ainfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String ainfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.aid
     *
     * @return the value of applicant.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.aid
     *
     * @param aid the value for applicant.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.aname
     *
     * @return the value of applicant.aname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.aname
     *
     * @param aname the value for applicant.aname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.acard
     *
     * @return the value of applicant.acard
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getAcard() {
        return acard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.acard
     *
     * @param acard the value for applicant.acard
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAcard(String acard) {
        this.acard = acard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.aadress
     *
     * @return the value of applicant.aadress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getAadress() {
        return aadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.aadress
     *
     * @param aadress the value for applicant.aadress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAadress(String aadress) {
        this.aadress = aadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.aphone
     *
     * @return the value of applicant.aphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getAphone() {
        return aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.aphone
     *
     * @param aphone the value for applicant.aphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAphone(String aphone) {
        this.aphone = aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applicant.ainfo
     *
     * @return the value of applicant.ainfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getAinfo() {
        return ainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applicant.ainfo
     *
     * @param ainfo the value for applicant.ainfo
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAinfo(String ainfo) {
        this.ainfo = ainfo;
    }

    @Override
    public String toString() {
        return "Applicant{" +
                "aid=" + aid +
                ", aname='" + aname + '\'' +
                ", acard='" + acard + '\'' +
                ", aadress='" + aadress + '\'' +
                ", aphone='" + aphone + '\'' +
                ", ainfo='" + ainfo + '\'' +
                '}';
    }
}