package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class ApplicantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public ApplicantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Integer value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Integer value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Integer value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Integer value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Integer value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Integer value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Integer> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Integer> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Integer value1, Integer value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Integer value1, Integer value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAnameIsNull() {
            addCriterion("aname is null");
            return (Criteria) this;
        }

        public Criteria andAnameIsNotNull() {
            addCriterion("aname is not null");
            return (Criteria) this;
        }

        public Criteria andAnameEqualTo(String value) {
            addCriterion("aname =", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotEqualTo(String value) {
            addCriterion("aname <>", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThan(String value) {
            addCriterion("aname >", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThanOrEqualTo(String value) {
            addCriterion("aname >=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThan(String value) {
            addCriterion("aname <", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThanOrEqualTo(String value) {
            addCriterion("aname <=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLike(String value) {
            addCriterion("aname like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotLike(String value) {
            addCriterion("aname not like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameIn(List<String> values) {
            addCriterion("aname in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotIn(List<String> values) {
            addCriterion("aname not in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameBetween(String value1, String value2) {
            addCriterion("aname between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotBetween(String value1, String value2) {
            addCriterion("aname not between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andAcardIsNull() {
            addCriterion("acard is null");
            return (Criteria) this;
        }

        public Criteria andAcardIsNotNull() {
            addCriterion("acard is not null");
            return (Criteria) this;
        }

        public Criteria andAcardEqualTo(String value) {
            addCriterion("acard =", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardNotEqualTo(String value) {
            addCriterion("acard <>", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardGreaterThan(String value) {
            addCriterion("acard >", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardGreaterThanOrEqualTo(String value) {
            addCriterion("acard >=", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardLessThan(String value) {
            addCriterion("acard <", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardLessThanOrEqualTo(String value) {
            addCriterion("acard <=", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardLike(String value) {
            addCriterion("acard like", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardNotLike(String value) {
            addCriterion("acard not like", value, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardIn(List<String> values) {
            addCriterion("acard in", values, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardNotIn(List<String> values) {
            addCriterion("acard not in", values, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardBetween(String value1, String value2) {
            addCriterion("acard between", value1, value2, "acard");
            return (Criteria) this;
        }

        public Criteria andAcardNotBetween(String value1, String value2) {
            addCriterion("acard not between", value1, value2, "acard");
            return (Criteria) this;
        }

        public Criteria andAadressIsNull() {
            addCriterion("aadress is null");
            return (Criteria) this;
        }

        public Criteria andAadressIsNotNull() {
            addCriterion("aadress is not null");
            return (Criteria) this;
        }

        public Criteria andAadressEqualTo(String value) {
            addCriterion("aadress =", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressNotEqualTo(String value) {
            addCriterion("aadress <>", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressGreaterThan(String value) {
            addCriterion("aadress >", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressGreaterThanOrEqualTo(String value) {
            addCriterion("aadress >=", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressLessThan(String value) {
            addCriterion("aadress <", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressLessThanOrEqualTo(String value) {
            addCriterion("aadress <=", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressLike(String value) {
            addCriterion("aadress like", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressNotLike(String value) {
            addCriterion("aadress not like", value, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressIn(List<String> values) {
            addCriterion("aadress in", values, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressNotIn(List<String> values) {
            addCriterion("aadress not in", values, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressBetween(String value1, String value2) {
            addCriterion("aadress between", value1, value2, "aadress");
            return (Criteria) this;
        }

        public Criteria andAadressNotBetween(String value1, String value2) {
            addCriterion("aadress not between", value1, value2, "aadress");
            return (Criteria) this;
        }

        public Criteria andAphoneIsNull() {
            addCriterion("aphone is null");
            return (Criteria) this;
        }

        public Criteria andAphoneIsNotNull() {
            addCriterion("aphone is not null");
            return (Criteria) this;
        }

        public Criteria andAphoneEqualTo(String value) {
            addCriterion("aphone =", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneNotEqualTo(String value) {
            addCriterion("aphone <>", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneGreaterThan(String value) {
            addCriterion("aphone >", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneGreaterThanOrEqualTo(String value) {
            addCriterion("aphone >=", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneLessThan(String value) {
            addCriterion("aphone <", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneLessThanOrEqualTo(String value) {
            addCriterion("aphone <=", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneLike(String value) {
            addCriterion("aphone like", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneNotLike(String value) {
            addCriterion("aphone not like", value, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneIn(List<String> values) {
            addCriterion("aphone in", values, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneNotIn(List<String> values) {
            addCriterion("aphone not in", values, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneBetween(String value1, String value2) {
            addCriterion("aphone between", value1, value2, "aphone");
            return (Criteria) this;
        }

        public Criteria andAphoneNotBetween(String value1, String value2) {
            addCriterion("aphone not between", value1, value2, "aphone");
            return (Criteria) this;
        }

        public Criteria andAinfoIsNull() {
            addCriterion("ainfo is null");
            return (Criteria) this;
        }

        public Criteria andAinfoIsNotNull() {
            addCriterion("ainfo is not null");
            return (Criteria) this;
        }

        public Criteria andAinfoEqualTo(String value) {
            addCriterion("ainfo =", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoNotEqualTo(String value) {
            addCriterion("ainfo <>", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoGreaterThan(String value) {
            addCriterion("ainfo >", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoGreaterThanOrEqualTo(String value) {
            addCriterion("ainfo >=", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoLessThan(String value) {
            addCriterion("ainfo <", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoLessThanOrEqualTo(String value) {
            addCriterion("ainfo <=", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoLike(String value) {
            addCriterion("ainfo like", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoNotLike(String value) {
            addCriterion("ainfo not like", value, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoIn(List<String> values) {
            addCriterion("ainfo in", values, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoNotIn(List<String> values) {
            addCriterion("ainfo not in", values, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoBetween(String value1, String value2) {
            addCriterion("ainfo between", value1, value2, "ainfo");
            return (Criteria) this;
        }

        public Criteria andAinfoNotBetween(String value1, String value2) {
            addCriterion("ainfo not between", value1, value2, "ainfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applicant
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applicant
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}