package com.woniu.housemanager.pojo;

import java.io.Serializable;
import java.util.List;

public class Areas implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areas.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer areaid;

    private List devision;

    public List getDevision() {
        return devision;
    }

    public void setDevision(List devision) {
        this.devision = devision;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areas.arename
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String arename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areas.areaid
     *
     * @return the value of areas.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areas.areaid
     *
     * @param areaid the value for areas.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areas.arename
     *
     * @return the value of areas.arename
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getArename() {
        return arename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areas.arename
     *
     * @param arename the value for areas.arename
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setArename(String arename) {
        this.arename = arename;
    }
}