package com.woniu.housemanager.pojo;

public class Buildinginfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer hpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer lpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer purposeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer devisionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.qiuid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer qiuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer structureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer mwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer diid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.lsid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer lsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer loudongid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.projectname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.landcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String landcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildinginfo.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String houseaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.buildingid
     *
     * @return the value of buildinginfo.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.buildingid
     *
     * @param buildingid the value for buildinginfo.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.areaid
     *
     * @return the value of buildinginfo.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.areaid
     *
     * @param areaid the value for buildinginfo.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.hpid
     *
     * @return the value of buildinginfo.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getHpid() {
        return hpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.hpid
     *
     * @param hpid the value for buildinginfo.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHpid(Integer hpid) {
        this.hpid = hpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.lpid
     *
     * @return the value of buildinginfo.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getLpid() {
        return lpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.lpid
     *
     * @param lpid the value for buildinginfo.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLpid(Integer lpid) {
        this.lpid = lpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.purposeid
     *
     * @return the value of buildinginfo.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getPurposeid() {
        return purposeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.purposeid
     *
     * @param purposeid the value for buildinginfo.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setPurposeid(Integer purposeid) {
        this.purposeid = purposeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.devisionid
     *
     * @return the value of buildinginfo.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getDevisionid() {
        return devisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.devisionid
     *
     * @param devisionid the value for buildinginfo.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDevisionid(Integer devisionid) {
        this.devisionid = devisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.qiuid
     *
     * @return the value of buildinginfo.qiuid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getQiuid() {
        return qiuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.qiuid
     *
     * @param qiuid the value for buildinginfo.qiuid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setQiuid(Integer qiuid) {
        this.qiuid = qiuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.structureid
     *
     * @return the value of buildinginfo.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getStructureid() {
        return structureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.structureid
     *
     * @param structureid the value for buildinginfo.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setStructureid(Integer structureid) {
        this.structureid = structureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.mwid
     *
     * @return the value of buildinginfo.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getMwid() {
        return mwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.mwid
     *
     * @param mwid the value for buildinginfo.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setMwid(Integer mwid) {
        this.mwid = mwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.diid
     *
     * @return the value of buildinginfo.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getDiid() {
        return diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.diid
     *
     * @param diid the value for buildinginfo.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDiid(Integer diid) {
        this.diid = diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.lsid
     *
     * @return the value of buildinginfo.lsid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getLsid() {
        return lsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.lsid
     *
     * @param lsid the value for buildinginfo.lsid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLsid(Integer lsid) {
        this.lsid = lsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.loudongid
     *
     * @return the value of buildinginfo.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getLoudongid() {
        return loudongid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.loudongid
     *
     * @param loudongid the value for buildinginfo.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLoudongid(Integer loudongid) {
        this.loudongid = loudongid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.projectname
     *
     * @return the value of buildinginfo.projectname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.projectname
     *
     * @param projectname the value for buildinginfo.projectname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.landcode
     *
     * @return the value of buildinginfo.landcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getLandcode() {
        return landcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.landcode
     *
     * @param landcode the value for buildinginfo.landcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLandcode(String landcode) {
        this.landcode = landcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildinginfo.houseaddress
     *
     * @return the value of buildinginfo.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getHouseaddress() {
        return houseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildinginfo.houseaddress
     *
     * @param houseaddress the value for buildinginfo.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHouseaddress(String houseaddress) {
        this.houseaddress = houseaddress;
    }
}