package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class BuildinginfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public BuildinginfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuildingidIsNull() {
            addCriterion("buildingid is null");
            return (Criteria) this;
        }

        public Criteria andBuildingidIsNotNull() {
            addCriterion("buildingid is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingidEqualTo(Integer value) {
            addCriterion("buildingid =", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidNotEqualTo(Integer value) {
            addCriterion("buildingid <>", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidGreaterThan(Integer value) {
            addCriterion("buildingid >", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidGreaterThanOrEqualTo(Integer value) {
            addCriterion("buildingid >=", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidLessThan(Integer value) {
            addCriterion("buildingid <", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidLessThanOrEqualTo(Integer value) {
            addCriterion("buildingid <=", value, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidIn(List<Integer> values) {
            addCriterion("buildingid in", values, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidNotIn(List<Integer> values) {
            addCriterion("buildingid not in", values, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidBetween(Integer value1, Integer value2) {
            addCriterion("buildingid between", value1, value2, "buildingid");
            return (Criteria) this;
        }

        public Criteria andBuildingidNotBetween(Integer value1, Integer value2) {
            addCriterion("buildingid not between", value1, value2, "buildingid");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaid is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaid is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(Integer value) {
            addCriterion("areaid =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(Integer value) {
            addCriterion("areaid <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(Integer value) {
            addCriterion("areaid >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("areaid >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(Integer value) {
            addCriterion("areaid <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("areaid <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<Integer> values) {
            addCriterion("areaid in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<Integer> values) {
            addCriterion("areaid not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(Integer value1, Integer value2) {
            addCriterion("areaid between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("areaid not between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andHpidIsNull() {
            addCriterion("hpid is null");
            return (Criteria) this;
        }

        public Criteria andHpidIsNotNull() {
            addCriterion("hpid is not null");
            return (Criteria) this;
        }

        public Criteria andHpidEqualTo(Integer value) {
            addCriterion("hpid =", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidNotEqualTo(Integer value) {
            addCriterion("hpid <>", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidGreaterThan(Integer value) {
            addCriterion("hpid >", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpid >=", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidLessThan(Integer value) {
            addCriterion("hpid <", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidLessThanOrEqualTo(Integer value) {
            addCriterion("hpid <=", value, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidIn(List<Integer> values) {
            addCriterion("hpid in", values, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidNotIn(List<Integer> values) {
            addCriterion("hpid not in", values, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidBetween(Integer value1, Integer value2) {
            addCriterion("hpid between", value1, value2, "hpid");
            return (Criteria) this;
        }

        public Criteria andHpidNotBetween(Integer value1, Integer value2) {
            addCriterion("hpid not between", value1, value2, "hpid");
            return (Criteria) this;
        }

        public Criteria andLpidIsNull() {
            addCriterion("lpid is null");
            return (Criteria) this;
        }

        public Criteria andLpidIsNotNull() {
            addCriterion("lpid is not null");
            return (Criteria) this;
        }

        public Criteria andLpidEqualTo(Integer value) {
            addCriterion("lpid =", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidNotEqualTo(Integer value) {
            addCriterion("lpid <>", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidGreaterThan(Integer value) {
            addCriterion("lpid >", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("lpid >=", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidLessThan(Integer value) {
            addCriterion("lpid <", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidLessThanOrEqualTo(Integer value) {
            addCriterion("lpid <=", value, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidIn(List<Integer> values) {
            addCriterion("lpid in", values, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidNotIn(List<Integer> values) {
            addCriterion("lpid not in", values, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidBetween(Integer value1, Integer value2) {
            addCriterion("lpid between", value1, value2, "lpid");
            return (Criteria) this;
        }

        public Criteria andLpidNotBetween(Integer value1, Integer value2) {
            addCriterion("lpid not between", value1, value2, "lpid");
            return (Criteria) this;
        }

        public Criteria andPurposeidIsNull() {
            addCriterion("purposeid is null");
            return (Criteria) this;
        }

        public Criteria andPurposeidIsNotNull() {
            addCriterion("purposeid is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeidEqualTo(Integer value) {
            addCriterion("purposeid =", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidNotEqualTo(Integer value) {
            addCriterion("purposeid <>", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidGreaterThan(Integer value) {
            addCriterion("purposeid >", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("purposeid >=", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidLessThan(Integer value) {
            addCriterion("purposeid <", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidLessThanOrEqualTo(Integer value) {
            addCriterion("purposeid <=", value, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidIn(List<Integer> values) {
            addCriterion("purposeid in", values, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidNotIn(List<Integer> values) {
            addCriterion("purposeid not in", values, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidBetween(Integer value1, Integer value2) {
            addCriterion("purposeid between", value1, value2, "purposeid");
            return (Criteria) this;
        }

        public Criteria andPurposeidNotBetween(Integer value1, Integer value2) {
            addCriterion("purposeid not between", value1, value2, "purposeid");
            return (Criteria) this;
        }

        public Criteria andDevisionidIsNull() {
            addCriterion("devisionid is null");
            return (Criteria) this;
        }

        public Criteria andDevisionidIsNotNull() {
            addCriterion("devisionid is not null");
            return (Criteria) this;
        }

        public Criteria andDevisionidEqualTo(Integer value) {
            addCriterion("devisionid =", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotEqualTo(Integer value) {
            addCriterion("devisionid <>", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidGreaterThan(Integer value) {
            addCriterion("devisionid >", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("devisionid >=", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidLessThan(Integer value) {
            addCriterion("devisionid <", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidLessThanOrEqualTo(Integer value) {
            addCriterion("devisionid <=", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidIn(List<Integer> values) {
            addCriterion("devisionid in", values, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotIn(List<Integer> values) {
            addCriterion("devisionid not in", values, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidBetween(Integer value1, Integer value2) {
            addCriterion("devisionid between", value1, value2, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotBetween(Integer value1, Integer value2) {
            addCriterion("devisionid not between", value1, value2, "devisionid");
            return (Criteria) this;
        }

        public Criteria andQiuidIsNull() {
            addCriterion("qiuid is null");
            return (Criteria) this;
        }

        public Criteria andQiuidIsNotNull() {
            addCriterion("qiuid is not null");
            return (Criteria) this;
        }

        public Criteria andQiuidEqualTo(Integer value) {
            addCriterion("qiuid =", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidNotEqualTo(Integer value) {
            addCriterion("qiuid <>", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidGreaterThan(Integer value) {
            addCriterion("qiuid >", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("qiuid >=", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidLessThan(Integer value) {
            addCriterion("qiuid <", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidLessThanOrEqualTo(Integer value) {
            addCriterion("qiuid <=", value, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidIn(List<Integer> values) {
            addCriterion("qiuid in", values, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidNotIn(List<Integer> values) {
            addCriterion("qiuid not in", values, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidBetween(Integer value1, Integer value2) {
            addCriterion("qiuid between", value1, value2, "qiuid");
            return (Criteria) this;
        }

        public Criteria andQiuidNotBetween(Integer value1, Integer value2) {
            addCriterion("qiuid not between", value1, value2, "qiuid");
            return (Criteria) this;
        }

        public Criteria andStructureidIsNull() {
            addCriterion("structureid is null");
            return (Criteria) this;
        }

        public Criteria andStructureidIsNotNull() {
            addCriterion("structureid is not null");
            return (Criteria) this;
        }

        public Criteria andStructureidEqualTo(Integer value) {
            addCriterion("structureid =", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidNotEqualTo(Integer value) {
            addCriterion("structureid <>", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidGreaterThan(Integer value) {
            addCriterion("structureid >", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidGreaterThanOrEqualTo(Integer value) {
            addCriterion("structureid >=", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidLessThan(Integer value) {
            addCriterion("structureid <", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidLessThanOrEqualTo(Integer value) {
            addCriterion("structureid <=", value, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidIn(List<Integer> values) {
            addCriterion("structureid in", values, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidNotIn(List<Integer> values) {
            addCriterion("structureid not in", values, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidBetween(Integer value1, Integer value2) {
            addCriterion("structureid between", value1, value2, "structureid");
            return (Criteria) this;
        }

        public Criteria andStructureidNotBetween(Integer value1, Integer value2) {
            addCriterion("structureid not between", value1, value2, "structureid");
            return (Criteria) this;
        }

        public Criteria andMwidIsNull() {
            addCriterion("mwid is null");
            return (Criteria) this;
        }

        public Criteria andMwidIsNotNull() {
            addCriterion("mwid is not null");
            return (Criteria) this;
        }

        public Criteria andMwidEqualTo(Integer value) {
            addCriterion("mwid =", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotEqualTo(Integer value) {
            addCriterion("mwid <>", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidGreaterThan(Integer value) {
            addCriterion("mwid >", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mwid >=", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidLessThan(Integer value) {
            addCriterion("mwid <", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidLessThanOrEqualTo(Integer value) {
            addCriterion("mwid <=", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidIn(List<Integer> values) {
            addCriterion("mwid in", values, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotIn(List<Integer> values) {
            addCriterion("mwid not in", values, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidBetween(Integer value1, Integer value2) {
            addCriterion("mwid between", value1, value2, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotBetween(Integer value1, Integer value2) {
            addCriterion("mwid not between", value1, value2, "mwid");
            return (Criteria) this;
        }

        public Criteria andDiidIsNull() {
            addCriterion("diid is null");
            return (Criteria) this;
        }

        public Criteria andDiidIsNotNull() {
            addCriterion("diid is not null");
            return (Criteria) this;
        }

        public Criteria andDiidEqualTo(Integer value) {
            addCriterion("diid =", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotEqualTo(Integer value) {
            addCriterion("diid <>", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidGreaterThan(Integer value) {
            addCriterion("diid >", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("diid >=", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidLessThan(Integer value) {
            addCriterion("diid <", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidLessThanOrEqualTo(Integer value) {
            addCriterion("diid <=", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidIn(List<Integer> values) {
            addCriterion("diid in", values, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotIn(List<Integer> values) {
            addCriterion("diid not in", values, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidBetween(Integer value1, Integer value2) {
            addCriterion("diid between", value1, value2, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotBetween(Integer value1, Integer value2) {
            addCriterion("diid not between", value1, value2, "diid");
            return (Criteria) this;
        }

        public Criteria andLsidIsNull() {
            addCriterion("lsid is null");
            return (Criteria) this;
        }

        public Criteria andLsidIsNotNull() {
            addCriterion("lsid is not null");
            return (Criteria) this;
        }

        public Criteria andLsidEqualTo(Integer value) {
            addCriterion("lsid =", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidNotEqualTo(Integer value) {
            addCriterion("lsid <>", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidGreaterThan(Integer value) {
            addCriterion("lsid >", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("lsid >=", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidLessThan(Integer value) {
            addCriterion("lsid <", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidLessThanOrEqualTo(Integer value) {
            addCriterion("lsid <=", value, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidIn(List<Integer> values) {
            addCriterion("lsid in", values, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidNotIn(List<Integer> values) {
            addCriterion("lsid not in", values, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidBetween(Integer value1, Integer value2) {
            addCriterion("lsid between", value1, value2, "lsid");
            return (Criteria) this;
        }

        public Criteria andLsidNotBetween(Integer value1, Integer value2) {
            addCriterion("lsid not between", value1, value2, "lsid");
            return (Criteria) this;
        }

        public Criteria andLoudongidIsNull() {
            addCriterion("loudongid is null");
            return (Criteria) this;
        }

        public Criteria andLoudongidIsNotNull() {
            addCriterion("loudongid is not null");
            return (Criteria) this;
        }

        public Criteria andLoudongidEqualTo(Integer value) {
            addCriterion("loudongid =", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidNotEqualTo(Integer value) {
            addCriterion("loudongid <>", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidGreaterThan(Integer value) {
            addCriterion("loudongid >", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidGreaterThanOrEqualTo(Integer value) {
            addCriterion("loudongid >=", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidLessThan(Integer value) {
            addCriterion("loudongid <", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidLessThanOrEqualTo(Integer value) {
            addCriterion("loudongid <=", value, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidIn(List<Integer> values) {
            addCriterion("loudongid in", values, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidNotIn(List<Integer> values) {
            addCriterion("loudongid not in", values, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidBetween(Integer value1, Integer value2) {
            addCriterion("loudongid between", value1, value2, "loudongid");
            return (Criteria) this;
        }

        public Criteria andLoudongidNotBetween(Integer value1, Integer value2) {
            addCriterion("loudongid not between", value1, value2, "loudongid");
            return (Criteria) this;
        }

        public Criteria andProjectnameIsNull() {
            addCriterion("projectname is null");
            return (Criteria) this;
        }

        public Criteria andProjectnameIsNotNull() {
            addCriterion("projectname is not null");
            return (Criteria) this;
        }

        public Criteria andProjectnameEqualTo(String value) {
            addCriterion("projectname =", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameNotEqualTo(String value) {
            addCriterion("projectname <>", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameGreaterThan(String value) {
            addCriterion("projectname >", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameGreaterThanOrEqualTo(String value) {
            addCriterion("projectname >=", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameLessThan(String value) {
            addCriterion("projectname <", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameLessThanOrEqualTo(String value) {
            addCriterion("projectname <=", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameLike(String value) {
            addCriterion("projectname like", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameNotLike(String value) {
            addCriterion("projectname not like", value, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameIn(List<String> values) {
            addCriterion("projectname in", values, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameNotIn(List<String> values) {
            addCriterion("projectname not in", values, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameBetween(String value1, String value2) {
            addCriterion("projectname between", value1, value2, "projectname");
            return (Criteria) this;
        }

        public Criteria andProjectnameNotBetween(String value1, String value2) {
            addCriterion("projectname not between", value1, value2, "projectname");
            return (Criteria) this;
        }

        public Criteria andLandcodeIsNull() {
            addCriterion("landcode is null");
            return (Criteria) this;
        }

        public Criteria andLandcodeIsNotNull() {
            addCriterion("landcode is not null");
            return (Criteria) this;
        }

        public Criteria andLandcodeEqualTo(String value) {
            addCriterion("landcode =", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeNotEqualTo(String value) {
            addCriterion("landcode <>", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeGreaterThan(String value) {
            addCriterion("landcode >", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeGreaterThanOrEqualTo(String value) {
            addCriterion("landcode >=", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeLessThan(String value) {
            addCriterion("landcode <", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeLessThanOrEqualTo(String value) {
            addCriterion("landcode <=", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeLike(String value) {
            addCriterion("landcode like", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeNotLike(String value) {
            addCriterion("landcode not like", value, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeIn(List<String> values) {
            addCriterion("landcode in", values, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeNotIn(List<String> values) {
            addCriterion("landcode not in", values, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeBetween(String value1, String value2) {
            addCriterion("landcode between", value1, value2, "landcode");
            return (Criteria) this;
        }

        public Criteria andLandcodeNotBetween(String value1, String value2) {
            addCriterion("landcode not between", value1, value2, "landcode");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIsNull() {
            addCriterion("houseaddress is null");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIsNotNull() {
            addCriterion("houseaddress is not null");
            return (Criteria) this;
        }

        public Criteria andHouseaddressEqualTo(String value) {
            addCriterion("houseaddress =", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotEqualTo(String value) {
            addCriterion("houseaddress <>", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressGreaterThan(String value) {
            addCriterion("houseaddress >", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressGreaterThanOrEqualTo(String value) {
            addCriterion("houseaddress >=", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLessThan(String value) {
            addCriterion("houseaddress <", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLessThanOrEqualTo(String value) {
            addCriterion("houseaddress <=", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLike(String value) {
            addCriterion("houseaddress like", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotLike(String value) {
            addCriterion("houseaddress not like", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIn(List<String> values) {
            addCriterion("houseaddress in", values, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotIn(List<String> values) {
            addCriterion("houseaddress not in", values, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressBetween(String value1, String value2) {
            addCriterion("houseaddress between", value1, value2, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotBetween(String value1, String value2) {
            addCriterion("houseaddress not between", value1, value2, "houseaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buildinginfo
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 10 19:57:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buildinginfo
     *
     * @mbggenerated Wed Jun 10 19:57:50 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}