package com.woniu.housemanager.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Bussnessstatus implements Serializable {
    private String bdname;
    private String workname;

    public String getBdname() {
        return bdname;
    }

    public void setBdname(String bdname) {
        this.bdname = bdname;
    }

    public String getWorkname() {
        return workname;
    }

    public void setWorkname(String workname) {
        this.workname = workname;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.bsid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private String bsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.hiid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private Integer hiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.mortgageid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private Integer mortgageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.workid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private Integer workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.housetransferid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private Integer housetransferid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.bsstatus
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private String bsstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.bsdate
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date bsdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.aname
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnessstatus.acard
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    private String acard;

    private WorkerInfo workerInfo;

    private HouseInfo houseInfo;

    public HouseInfo getHouseInfo() {
        return houseInfo;
    }

    public void setHouseInfo(HouseInfo houseInfo) {
        this.houseInfo = houseInfo;
    }

    public WorkerInfo getWorkerInfo() {
        return workerInfo;
    }

    public void setWorkerInfo(WorkerInfo workerInfo) {
        this.workerInfo = workerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.bsid
     *
     * @return the value of bussnessstatus.bsid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public String getBsid() {
        return bsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.bsid
     *
     * @param bsid the value for bussnessstatus.bsid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setBsid(String bsid) {
        this.bsid = bsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.hiid
     *
     * @return the value of bussnessstatus.hiid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public Integer getHiid() {
        return hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.hiid
     *
     * @param hiid the value for bussnessstatus.hiid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setHiid(Integer hiid) {
        this.hiid = hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.mortgageid
     *
     * @return the value of bussnessstatus.mortgageid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public Integer getMortgageid() {
        return mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.mortgageid
     *
     * @param mortgageid the value for bussnessstatus.mortgageid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setMortgageid(Integer mortgageid) {
        this.mortgageid = mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.workid
     *
     * @return the value of bussnessstatus.workid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.workid
     *
     * @param workid the value for bussnessstatus.workid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.housetransferid
     *
     * @return the value of bussnessstatus.housetransferid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public Integer getHousetransferid() {
        return housetransferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.housetransferid
     *
     * @param housetransferid the value for bussnessstatus.housetransferid
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setHousetransferid(Integer housetransferid) {
        this.housetransferid = housetransferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.bsstatus
     *
     * @return the value of bussnessstatus.bsstatus
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public String getBsstatus() {
        return bsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.bsstatus
     *
     * @param bsstatus the value for bussnessstatus.bsstatus
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setBsstatus(String bsstatus) {
        this.bsstatus = bsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.bsdate
     *
     * @return the value of bussnessstatus.bsdate
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public Date getBsdate() {
        return bsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.bsdate
     *
     * @param bsdate the value for bussnessstatus.bsdate
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setBsdate(Date bsdate) {
        this.bsdate = bsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.aname
     *
     * @return the value of bussnessstatus.aname
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.aname
     *
     * @param aname the value for bussnessstatus.aname
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnessstatus.acard
     *
     * @return the value of bussnessstatus.acard
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public String getAcard() {
        return acard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnessstatus.acard
     *
     * @param acard the value for bussnessstatus.acard
     *
     * @mbggenerated Thu Jun 11 20:40:54 CST 2020
     */
    public void setAcard(String acard) {
        this.acard = acard;
    }
}