package com.woniu.housemanager.pojo;

public class Bussnesstype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnesstype.btid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer btid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussnesstype.btname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String btname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnesstype.btid
     *
     * @return the value of bussnesstype.btid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getBtid() {
        return btid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnesstype.btid
     *
     * @param btid the value for bussnesstype.btid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setBtid(Integer btid) {
        this.btid = btid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussnesstype.btname
     *
     * @return the value of bussnesstype.btname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getBtname() {
        return btname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussnesstype.btname
     *
     * @param btname the value for bussnesstype.btname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setBtname(String btname) {
        this.btname = btname;
    }
}