package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class CheckesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public CheckesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCheckidIsNull() {
            addCriterion("checkid is null");
            return (Criteria) this;
        }

        public Criteria andCheckidIsNotNull() {
            addCriterion("checkid is not null");
            return (Criteria) this;
        }

        public Criteria andCheckidEqualTo(Integer value) {
            addCriterion("checkid =", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidNotEqualTo(Integer value) {
            addCriterion("checkid <>", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidGreaterThan(Integer value) {
            addCriterion("checkid >", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidGreaterThanOrEqualTo(Integer value) {
            addCriterion("checkid >=", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidLessThan(Integer value) {
            addCriterion("checkid <", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidLessThanOrEqualTo(Integer value) {
            addCriterion("checkid <=", value, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidIn(List<Integer> values) {
            addCriterion("checkid in", values, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidNotIn(List<Integer> values) {
            addCriterion("checkid not in", values, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidBetween(Integer value1, Integer value2) {
            addCriterion("checkid between", value1, value2, "checkid");
            return (Criteria) this;
        }

        public Criteria andCheckidNotBetween(Integer value1, Integer value2) {
            addCriterion("checkid not between", value1, value2, "checkid");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andCheckpathIsNull() {
            addCriterion("checkpath is null");
            return (Criteria) this;
        }

        public Criteria andCheckpathIsNotNull() {
            addCriterion("checkpath is not null");
            return (Criteria) this;
        }

        public Criteria andCheckpathEqualTo(String value) {
            addCriterion("checkpath =", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathNotEqualTo(String value) {
            addCriterion("checkpath <>", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathGreaterThan(String value) {
            addCriterion("checkpath >", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathGreaterThanOrEqualTo(String value) {
            addCriterion("checkpath >=", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathLessThan(String value) {
            addCriterion("checkpath <", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathLessThanOrEqualTo(String value) {
            addCriterion("checkpath <=", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathLike(String value) {
            addCriterion("checkpath like", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathNotLike(String value) {
            addCriterion("checkpath not like", value, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathIn(List<String> values) {
            addCriterion("checkpath in", values, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathNotIn(List<String> values) {
            addCriterion("checkpath not in", values, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathBetween(String value1, String value2) {
            addCriterion("checkpath between", value1, value2, "checkpath");
            return (Criteria) this;
        }

        public Criteria andCheckpathNotBetween(String value1, String value2) {
            addCriterion("checkpath not between", value1, value2, "checkpath");
            return (Criteria) this;
        }

        public Criteria andHiidIsNull() {
            addCriterion("hiid is null");
            return (Criteria) this;
        }

        public Criteria andHiidIsNotNull() {
            addCriterion("hiid is not null");
            return (Criteria) this;
        }

        public Criteria andHiidEqualTo(Integer value) {
            addCriterion("hiid =", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidNotEqualTo(Integer value) {
            addCriterion("hiid <>", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidGreaterThan(Integer value) {
            addCriterion("hiid >", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("hiid >=", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidLessThan(Integer value) {
            addCriterion("hiid <", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidLessThanOrEqualTo(Integer value) {
            addCriterion("hiid <=", value, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidIn(List<Integer> values) {
            addCriterion("hiid in", values, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidNotIn(List<Integer> values) {
            addCriterion("hiid not in", values, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidBetween(Integer value1, Integer value2) {
            addCriterion("hiid between", value1, value2, "hiid");
            return (Criteria) this;
        }

        public Criteria andHiidNotBetween(Integer value1, Integer value2) {
            addCriterion("hiid not between", value1, value2, "hiid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkes
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 17 19:41:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkes
     *
     * @mbggenerated Wed Jun 17 19:41:29 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}