package com.woniu.housemanager.pojo;

public class Commoninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoninfo.commonid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer commonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoninfo.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoninfo.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer gpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoninfo.commonway
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String commonway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoninfo.commonshare
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String commonshare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoninfo.commonid
     *
     * @return the value of commoninfo.commonid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getCommonid() {
        return commonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoninfo.commonid
     *
     * @param commonid the value for commoninfo.commonid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCommonid(Integer commonid) {
        this.commonid = commonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoninfo.aid
     *
     * @return the value of commoninfo.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoninfo.aid
     *
     * @param aid the value for commoninfo.aid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoninfo.gpid
     *
     * @return the value of commoninfo.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getGpid() {
        return gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoninfo.gpid
     *
     * @param gpid the value for commoninfo.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setGpid(Integer gpid) {
        this.gpid = gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoninfo.commonway
     *
     * @return the value of commoninfo.commonway
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCommonway() {
        return commonway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoninfo.commonway
     *
     * @param commonway the value for commoninfo.commonway
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCommonway(String commonway) {
        this.commonway = commonway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoninfo.commonshare
     *
     * @return the value of commoninfo.commonshare
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCommonshare() {
        return commonshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoninfo.commonshare
     *
     * @param commonshare the value for commoninfo.commonshare
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCommonshare(String commonshare) {
        this.commonshare = commonshare;
    }
}