package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class Devision implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devision.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer devisionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devision.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devision.devisionname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String devisionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devision.devisionid
     *
     * @return the value of devision.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getDevisionid() {
        return devisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devision.devisionid
     *
     * @param devisionid the value for devision.devisionid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDevisionid(Integer devisionid) {
        this.devisionid = devisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devision.areaid
     *
     * @return the value of devision.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devision.areaid
     *
     * @param areaid the value for devision.areaid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devision.devisionname
     *
     * @return the value of devision.devisionname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getDevisionname() {
        return devisionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devision.devisionname
     *
     * @param devisionname the value for devision.devisionname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDevisionname(String devisionname) {
        this.devisionname = devisionname;
    }
}