package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class DevisionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public DevisionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDevisionidIsNull() {
            addCriterion("devisionid is null");
            return (Criteria) this;
        }

        public Criteria andDevisionidIsNotNull() {
            addCriterion("devisionid is not null");
            return (Criteria) this;
        }

        public Criteria andDevisionidEqualTo(Integer value) {
            addCriterion("devisionid =", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotEqualTo(Integer value) {
            addCriterion("devisionid <>", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidGreaterThan(Integer value) {
            addCriterion("devisionid >", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("devisionid >=", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidLessThan(Integer value) {
            addCriterion("devisionid <", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidLessThanOrEqualTo(Integer value) {
            addCriterion("devisionid <=", value, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidIn(List<Integer> values) {
            addCriterion("devisionid in", values, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotIn(List<Integer> values) {
            addCriterion("devisionid not in", values, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidBetween(Integer value1, Integer value2) {
            addCriterion("devisionid between", value1, value2, "devisionid");
            return (Criteria) this;
        }

        public Criteria andDevisionidNotBetween(Integer value1, Integer value2) {
            addCriterion("devisionid not between", value1, value2, "devisionid");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaid is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaid is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(Integer value) {
            addCriterion("areaid =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(Integer value) {
            addCriterion("areaid <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(Integer value) {
            addCriterion("areaid >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("areaid >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(Integer value) {
            addCriterion("areaid <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("areaid <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<Integer> values) {
            addCriterion("areaid in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<Integer> values) {
            addCriterion("areaid not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(Integer value1, Integer value2) {
            addCriterion("areaid between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("areaid not between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andDevisionnameIsNull() {
            addCriterion("devisionname is null");
            return (Criteria) this;
        }

        public Criteria andDevisionnameIsNotNull() {
            addCriterion("devisionname is not null");
            return (Criteria) this;
        }

        public Criteria andDevisionnameEqualTo(String value) {
            addCriterion("devisionname =", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameNotEqualTo(String value) {
            addCriterion("devisionname <>", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameGreaterThan(String value) {
            addCriterion("devisionname >", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameGreaterThanOrEqualTo(String value) {
            addCriterion("devisionname >=", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameLessThan(String value) {
            addCriterion("devisionname <", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameLessThanOrEqualTo(String value) {
            addCriterion("devisionname <=", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameLike(String value) {
            addCriterion("devisionname like", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameNotLike(String value) {
            addCriterion("devisionname not like", value, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameIn(List<String> values) {
            addCriterion("devisionname in", values, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameNotIn(List<String> values) {
            addCriterion("devisionname not in", values, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameBetween(String value1, String value2) {
            addCriterion("devisionname between", value1, value2, "devisionname");
            return (Criteria) this;
        }

        public Criteria andDevisionnameNotBetween(String value1, String value2) {
            addCriterion("devisionname not between", value1, value2, "devisionname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devision
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devision
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}