package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class GetPeople implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getpeople.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer gpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getpeople.gpcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String gpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getpeople.gpphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String gpphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getpeople.gpid
     *
     * @return the value of getpeople.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getGpid() {
        return gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getpeople.gpid
     *
     * @param gpid the value for getpeople.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setGpid(Integer gpid) {
        this.gpid = gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getpeople.gpcode
     *
     * @return the value of getpeople.gpcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getGpcode() {
        return gpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getpeople.gpcode
     *
     * @param gpcode the value for getpeople.gpcode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setGpcode(String gpcode) {
        this.gpcode = gpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getpeople.gpphone
     *
     * @return the value of getpeople.gpphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getGpphone() {
        return gpphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getpeople.gpphone
     *
     * @param gpphone the value for getpeople.gpphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setGpphone(String gpphone) {
        this.gpphone = gpphone;
    }
}