package com.woniu.housemanager.pojo;

public class HouseNumber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housenumber.hnid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer hnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housenumber.hncode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String hncode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housenumber.hnid
     *
     * @return the value of housenumber.hnid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getHnid() {
        return hnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housenumber.hnid
     *
     * @param hnid the value for housenumber.hnid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHnid(Integer hnid) {
        this.hnid = hnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housenumber.hncode
     *
     * @return the value of housenumber.hncode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getHncode() {
        return hncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housenumber.hncode
     *
     * @param hncode the value for housenumber.hncode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHncode(String hncode) {
        this.hncode = hncode;
    }
}