package com.woniu.housemanager.pojo;

public class HouseProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houseproperty.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer hpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houseproperty.hpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String hpname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houseproperty.hpid
     *
     * @return the value of houseproperty.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getHpid() {
        return hpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houseproperty.hpid
     *
     * @param hpid the value for houseproperty.hpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHpid(Integer hpid) {
        this.hpid = hpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houseproperty.hpname
     *
     * @return the value of houseproperty.hpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getHpname() {
        return hpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houseproperty.hpname
     *
     * @param hpname the value for houseproperty.hpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHpname(String hpname) {
        this.hpname = hpname;
    }
}