package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class HouseTransfer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housetransfer.housetransferid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer housetransferid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housetransfer.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer gpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housetransfer.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer hiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housetransfer.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer bdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column housetransfer.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer checkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housetransfer.housetransferid
     *
     * @return the value of housetransfer.housetransferid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getHousetransferid() {
        return housetransferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housetransfer.housetransferid
     *
     * @param housetransferid the value for housetransfer.housetransferid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHousetransferid(Integer housetransferid) {
        this.housetransferid = housetransferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housetransfer.gpid
     *
     * @return the value of housetransfer.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getGpid() {
        return gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housetransfer.gpid
     *
     * @param gpid the value for housetransfer.gpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setGpid(Integer gpid) {
        this.gpid = gpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housetransfer.hiid
     *
     * @return the value of housetransfer.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getHiid() {
        return hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housetransfer.hiid
     *
     * @param hiid the value for housetransfer.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setHiid(Integer hiid) {
        this.hiid = hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housetransfer.bdid
     *
     * @return the value of housetransfer.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getBdid() {
        return bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housetransfer.bdid
     *
     * @param bdid the value for housetransfer.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setBdid(Integer bdid) {
        this.bdid = bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column housetransfer.checkid
     *
     * @return the value of housetransfer.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column housetransfer.checkid
     *
     * @param checkid the value for housetransfer.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCheckid(Integer checkid) {
        this.checkid = checkid;
    }
}