package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class KaiFaShangExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public KaiFaShangExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDiidIsNull() {
            addCriterion("diid is null");
            return (Criteria) this;
        }

        public Criteria andDiidIsNotNull() {
            addCriterion("diid is not null");
            return (Criteria) this;
        }

        public Criteria andDiidEqualTo(Integer value) {
            addCriterion("diid =", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotEqualTo(Integer value) {
            addCriterion("diid <>", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidGreaterThan(Integer value) {
            addCriterion("diid >", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("diid >=", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidLessThan(Integer value) {
            addCriterion("diid <", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidLessThanOrEqualTo(Integer value) {
            addCriterion("diid <=", value, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidIn(List<Integer> values) {
            addCriterion("diid in", values, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotIn(List<Integer> values) {
            addCriterion("diid not in", values, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidBetween(Integer value1, Integer value2) {
            addCriterion("diid between", value1, value2, "diid");
            return (Criteria) this;
        }

        public Criteria andDiidNotBetween(Integer value1, Integer value2) {
            addCriterion("diid not between", value1, value2, "diid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCompanybossIsNull() {
            addCriterion("companyboss is null");
            return (Criteria) this;
        }

        public Criteria andCompanybossIsNotNull() {
            addCriterion("companyboss is not null");
            return (Criteria) this;
        }

        public Criteria andCompanybossEqualTo(String value) {
            addCriterion("companyboss =", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossNotEqualTo(String value) {
            addCriterion("companyboss <>", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossGreaterThan(String value) {
            addCriterion("companyboss >", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossGreaterThanOrEqualTo(String value) {
            addCriterion("companyboss >=", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossLessThan(String value) {
            addCriterion("companyboss <", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossLessThanOrEqualTo(String value) {
            addCriterion("companyboss <=", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossLike(String value) {
            addCriterion("companyboss like", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossNotLike(String value) {
            addCriterion("companyboss not like", value, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossIn(List<String> values) {
            addCriterion("companyboss in", values, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossNotIn(List<String> values) {
            addCriterion("companyboss not in", values, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossBetween(String value1, String value2) {
            addCriterion("companyboss between", value1, value2, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanybossNotBetween(String value1, String value2) {
            addCriterion("companyboss not between", value1, value2, "companyboss");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("companycode is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("companycode is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("companycode =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("companycode <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("companycode >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("companycode >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("companycode <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("companycode <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("companycode like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("companycode not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("companycode in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("companycode not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("companycode between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("companycode not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressIsNull() {
            addCriterion("companyaddress is null");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressIsNotNull() {
            addCriterion("companyaddress is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressEqualTo(String value) {
            addCriterion("companyaddress =", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressNotEqualTo(String value) {
            addCriterion("companyaddress <>", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressGreaterThan(String value) {
            addCriterion("companyaddress >", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressGreaterThanOrEqualTo(String value) {
            addCriterion("companyaddress >=", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressLessThan(String value) {
            addCriterion("companyaddress <", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressLessThanOrEqualTo(String value) {
            addCriterion("companyaddress <=", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressLike(String value) {
            addCriterion("companyaddress like", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressNotLike(String value) {
            addCriterion("companyaddress not like", value, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressIn(List<String> values) {
            addCriterion("companyaddress in", values, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressNotIn(List<String> values) {
            addCriterion("companyaddress not in", values, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressBetween(String value1, String value2) {
            addCriterion("companyaddress between", value1, value2, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyaddressNotBetween(String value1, String value2) {
            addCriterion("companyaddress not between", value1, value2, "companyaddress");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneIsNull() {
            addCriterion("companyphone is null");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneIsNotNull() {
            addCriterion("companyphone is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneEqualTo(String value) {
            addCriterion("companyphone =", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneNotEqualTo(String value) {
            addCriterion("companyphone <>", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneGreaterThan(String value) {
            addCriterion("companyphone >", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneGreaterThanOrEqualTo(String value) {
            addCriterion("companyphone >=", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneLessThan(String value) {
            addCriterion("companyphone <", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneLessThanOrEqualTo(String value) {
            addCriterion("companyphone <=", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneLike(String value) {
            addCriterion("companyphone like", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneNotLike(String value) {
            addCriterion("companyphone not like", value, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneIn(List<String> values) {
            addCriterion("companyphone in", values, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneNotIn(List<String> values) {
            addCriterion("companyphone not in", values, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneBetween(String value1, String value2) {
            addCriterion("companyphone between", value1, value2, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyphoneNotBetween(String value1, String value2) {
            addCriterion("companyphone not between", value1, value2, "companyphone");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersIsNull() {
            addCriterion("companyworkers is null");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersIsNotNull() {
            addCriterion("companyworkers is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersEqualTo(Integer value) {
            addCriterion("companyworkers =", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersNotEqualTo(Integer value) {
            addCriterion("companyworkers <>", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersGreaterThan(Integer value) {
            addCriterion("companyworkers >", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersGreaterThanOrEqualTo(Integer value) {
            addCriterion("companyworkers >=", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersLessThan(Integer value) {
            addCriterion("companyworkers <", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersLessThanOrEqualTo(Integer value) {
            addCriterion("companyworkers <=", value, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersIn(List<Integer> values) {
            addCriterion("companyworkers in", values, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersNotIn(List<Integer> values) {
            addCriterion("companyworkers not in", values, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersBetween(Integer value1, Integer value2) {
            addCriterion("companyworkers between", value1, value2, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanyworkersNotBetween(Integer value1, Integer value2) {
            addCriterion("companyworkers not between", value1, value2, "companyworkers");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNull() {
            addCriterion("companyname is null");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNotNull() {
            addCriterion("companyname is not null");
            return (Criteria) this;
        }

        public Criteria andCompanynameEqualTo(String value) {
            addCriterion("companyname =", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotEqualTo(String value) {
            addCriterion("companyname <>", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThan(String value) {
            addCriterion("companyname >", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThanOrEqualTo(String value) {
            addCriterion("companyname >=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThan(String value) {
            addCriterion("companyname <", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThanOrEqualTo(String value) {
            addCriterion("companyname <=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLike(String value) {
            addCriterion("companyname like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotLike(String value) {
            addCriterion("companyname not like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameIn(List<String> values) {
            addCriterion("companyname in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotIn(List<String> values) {
            addCriterion("companyname not in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameBetween(String value1, String value2) {
            addCriterion("companyname between", value1, value2, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotBetween(String value1, String value2) {
            addCriterion("companyname not between", value1, value2, "companyname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kaifashang
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kaifashang
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}