package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class KaiFaShang implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer diid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.uid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companyboss
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String companyboss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companycode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companyaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companyphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String companyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companyworkers
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer companyworkers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaifashang.companyname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.diid
     *
     * @return the value of kaifashang.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getDiid() {
        return diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.diid
     *
     * @param diid the value for kaifashang.diid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setDiid(Integer diid) {
        this.diid = diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.uid
     *
     * @return the value of kaifashang.uid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.uid
     *
     * @param uid the value for kaifashang.uid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companyboss
     *
     * @return the value of kaifashang.companyboss
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCompanyboss() {
        return companyboss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companyboss
     *
     * @param companyboss the value for kaifashang.companyboss
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanyboss(String companyboss) {
        this.companyboss = companyboss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companycode
     *
     * @return the value of kaifashang.companycode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companycode
     *
     * @param companycode the value for kaifashang.companycode
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companyaddress
     *
     * @return the value of kaifashang.companyaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companyaddress
     *
     * @param companyaddress the value for kaifashang.companyaddress
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companyphone
     *
     * @return the value of kaifashang.companyphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCompanyphone() {
        return companyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companyphone
     *
     * @param companyphone the value for kaifashang.companyphone
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanyphone(String companyphone) {
        this.companyphone = companyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companyworkers
     *
     * @return the value of kaifashang.companyworkers
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getCompanyworkers() {
        return companyworkers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companyworkers
     *
     * @param companyworkers the value for kaifashang.companyworkers
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanyworkers(Integer companyworkers) {
        this.companyworkers = companyworkers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaifashang.companyname
     *
     * @return the value of kaifashang.companyname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaifashang.companyname
     *
     * @param companyname the value for kaifashang.companyname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
}