package com.woniu.housemanager.pojo;

public class LandProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column landproperty.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private Integer lpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column landproperty.lpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    private String lpname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column landproperty.lpid
     *
     * @return the value of landproperty.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public Integer getLpid() {
        return lpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column landproperty.lpid
     *
     * @param lpid the value for landproperty.lpid
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLpid(Integer lpid) {
        this.lpid = lpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column landproperty.lpname
     *
     * @return the value of landproperty.lpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public String getLpname() {
        return lpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column landproperty.lpname
     *
     * @param lpname the value for landproperty.lpname
     *
     * @mbggenerated Sun Jun 07 17:07:38 CST 2020
     */
    public void setLpname(String lpname) {
        this.lpname = lpname;
    }
}