package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class Layer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layer.layerid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer layerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layer.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer loudongid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layer.layhouses
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer layhouses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layer.layerarea
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Long layerarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column layer.laycode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer laycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layer.layerid
     *
     * @return the value of layer.layerid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getLayerid() {
        return layerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layer.layerid
     *
     * @param layerid the value for layer.layerid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLayerid(Integer layerid) {
        this.layerid = layerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layer.loudongid
     *
     * @return the value of layer.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getLoudongid() {
        return loudongid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layer.loudongid
     *
     * @param loudongid the value for layer.loudongid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLoudongid(Integer loudongid) {
        this.loudongid = loudongid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layer.layhouses
     *
     * @return the value of layer.layhouses
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getLayhouses() {
        return layhouses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layer.layhouses
     *
     * @param layhouses the value for layer.layhouses
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLayhouses(Integer layhouses) {
        this.layhouses = layhouses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layer.layerarea
     *
     * @return the value of layer.layerarea
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Long getLayerarea() {
        return layerarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layer.layerarea
     *
     * @param layerarea the value for layer.layerarea
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLayerarea(Long layerarea) {
        this.layerarea = layerarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column layer.laycode
     *
     * @return the value of layer.laycode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getLaycode() {
        return laycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column layer.laycode
     *
     * @param laycode the value for layer.laycode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLaycode(Integer laycode) {
        this.laycode = laycode;
    }
}