package com.woniu.housemanager.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class LouDong {
    private Integer loudongid;
    private String loudongname;
    private String loudongcode;
    private Integer countlayer;
    private String counthouses;
    private Long countarea;
    private String info;
    private Integer buildingid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loudong.countarea
     *
     * @return the value of loudong.countarea
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Long getCountarea() {
        return countarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loudong.countarea
     *
     * @param countarea the value for loudong.countarea
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setCountarea(Long countarea) {
        this.countarea = countarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loudong.info
     *
     * @return the value of loudong.info
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loudong.info
     *
     * @param info the value for loudong.info
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setInfo(String info) {
        this.info = info;
    }
}