package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class LouPanManager implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupanmanger.loupanmanager
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String loupanmanager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupanmanger.diid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer diid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupanmanger.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupanmanger.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer pspid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupanmanger.loupanstatus
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String loupanstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupanmanger.loupanmanager
     *
     * @return the value of loupanmanger.loupanmanager
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getLoupanmanager() {
        return loupanmanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupanmanger.loupanmanager
     *
     * @param loupanmanager the value for loupanmanger.loupanmanager
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLoupanmanager(String loupanmanager) {
        this.loupanmanager = loupanmanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupanmanger.diid
     *
     * @return the value of loupanmanger.diid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getDiid() {
        return diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupanmanger.diid
     *
     * @param diid the value for loupanmanger.diid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setDiid(Integer diid) {
        this.diid = diid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupanmanger.buildingid
     *
     * @return the value of loupanmanger.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupanmanger.buildingid
     *
     * @param buildingid the value for loupanmanger.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupanmanger.pspid
     *
     * @return the value of loupanmanger.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getPspid() {
        return pspid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupanmanger.pspid
     *
     * @param pspid the value for loupanmanger.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setPspid(Integer pspid) {
        this.pspid = pspid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupanmanger.loupanstatus
     *
     * @return the value of loupanmanger.loupanstatus
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getLoupanstatus() {
        return loupanstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupanmanger.loupanstatus
     *
     * @param loupanstatus the value for loupanmanger.loupanstatus
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setLoupanstatus(String loupanstatus) {
        this.loupanstatus = loupanstatus;
    }
}