package com.woniu.housemanager.pojo;

import java.util.ArrayList;
import java.util.List;

public class MakeWayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public MakeWayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMwidIsNull() {
            addCriterion("mwid is null");
            return (Criteria) this;
        }

        public Criteria andMwidIsNotNull() {
            addCriterion("mwid is not null");
            return (Criteria) this;
        }

        public Criteria andMwidEqualTo(Integer value) {
            addCriterion("mwid =", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotEqualTo(Integer value) {
            addCriterion("mwid <>", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidGreaterThan(Integer value) {
            addCriterion("mwid >", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mwid >=", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidLessThan(Integer value) {
            addCriterion("mwid <", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidLessThanOrEqualTo(Integer value) {
            addCriterion("mwid <=", value, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidIn(List<Integer> values) {
            addCriterion("mwid in", values, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotIn(List<Integer> values) {
            addCriterion("mwid not in", values, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidBetween(Integer value1, Integer value2) {
            addCriterion("mwid between", value1, value2, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwidNotBetween(Integer value1, Integer value2) {
            addCriterion("mwid not between", value1, value2, "mwid");
            return (Criteria) this;
        }

        public Criteria andMwnameIsNull() {
            addCriterion("mwname is null");
            return (Criteria) this;
        }

        public Criteria andMwnameIsNotNull() {
            addCriterion("mwname is not null");
            return (Criteria) this;
        }

        public Criteria andMwnameEqualTo(String value) {
            addCriterion("mwname =", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameNotEqualTo(String value) {
            addCriterion("mwname <>", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameGreaterThan(String value) {
            addCriterion("mwname >", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameGreaterThanOrEqualTo(String value) {
            addCriterion("mwname >=", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameLessThan(String value) {
            addCriterion("mwname <", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameLessThanOrEqualTo(String value) {
            addCriterion("mwname <=", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameLike(String value) {
            addCriterion("mwname like", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameNotLike(String value) {
            addCriterion("mwname not like", value, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameIn(List<String> values) {
            addCriterion("mwname in", values, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameNotIn(List<String> values) {
            addCriterion("mwname not in", values, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameBetween(String value1, String value2) {
            addCriterion("mwname between", value1, value2, "mwname");
            return (Criteria) this;
        }

        public Criteria andMwnameNotBetween(String value1, String value2) {
            addCriterion("mwname not between", value1, value2, "mwname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table makeway
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 07 17:07:39 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table makeway
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}