package com.woniu.housemanager.pojo;

public class MakeWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column makeway.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer mwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column makeway.mwname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String mwname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column makeway.mwid
     *
     * @return the value of makeway.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getMwid() {
        return mwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column makeway.mwid
     *
     * @param mwid the value for makeway.mwid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMwid(Integer mwid) {
        this.mwid = mwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column makeway.mwname
     *
     * @return the value of makeway.mwname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getMwname() {
        return mwname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column makeway.mwname
     *
     * @param mwname the value for makeway.mwname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMwname(String mwname) {
        this.mwname = mwname;
    }
}