package com.woniu.housemanager.pojo;

public class MortgagesTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgagestransfer.mtid
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    private Integer mtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgagestransfer.debt
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    private Integer debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgagestransfer.mtname
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    private String mtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgagestransfer.mtcard
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    private String mtcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgagestransfer.mtphone
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    private String mtphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgagestransfer.mtid
     *
     * @return the value of mortgagestransfer.mtid
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public Integer getMtid() {
        return mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgagestransfer.mtid
     *
     * @param mtid the value for mortgagestransfer.mtid
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public void setMtid(Integer mtid) {
        this.mtid = mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgagestransfer.debt
     *
     * @return the value of mortgagestransfer.debt
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public Integer getDebt() {
        return debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgagestransfer.debt
     *
     * @param debt the value for mortgagestransfer.debt
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public void setDebt(Integer debt) {
        this.debt = debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgagestransfer.mtname
     *
     * @return the value of mortgagestransfer.mtname
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public String getMtname() {
        return mtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgagestransfer.mtname
     *
     * @param mtname the value for mortgagestransfer.mtname
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public void setMtname(String mtname) {
        this.mtname = mtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgagestransfer.mtcard
     *
     * @return the value of mortgagestransfer.mtcard
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public String getMtcard() {
        return mtcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgagestransfer.mtcard
     *
     * @param mtcard the value for mortgagestransfer.mtcard
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public void setMtcard(String mtcard) {
        this.mtcard = mtcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgagestransfer.mtphone
     *
     * @return the value of mortgagestransfer.mtphone
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public String getMtphone() {
        return mtphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgagestransfer.mtphone
     *
     * @param mtphone the value for mortgagestransfer.mtphone
     *
     * @mbggenerated Sat Jun 13 14:29:12 CST 2020
     */
    public void setMtphone(String mtphone) {
        this.mtphone = mtphone;
    }
}