package com.woniu.housemanager.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Mortgage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgageid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer mortgageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer hiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.debt
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer bdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer checkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgagemoney
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private BigDecimal mortgagemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgagescope
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String mortgagescope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgagestart
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Date mortgagestart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgageend
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Date mortgageend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgage.mortgagecode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String mortgagecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgageid
     *
     * @return the value of mortgage.mortgageid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getMortgageid() {
        return mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgageid
     *
     * @param mortgageid the value for mortgage.mortgageid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgageid(Integer mortgageid) {
        this.mortgageid = mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.hiid
     *
     * @return the value of mortgage.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getHiid() {
        return hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.hiid
     *
     * @param hiid the value for mortgage.hiid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setHiid(Integer hiid) {
        this.hiid = hiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.debt
     *
     * @return the value of mortgage.debt
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getDebt() {
        return debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.debt
     *
     * @param debt the value for mortgage.debt
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setDebt(Integer debt) {
        this.debt = debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.bdid
     *
     * @return the value of mortgage.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getBdid() {
        return bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.bdid
     *
     * @param bdid the value for mortgage.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setBdid(Integer bdid) {
        this.bdid = bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.checkid
     *
     * @return the value of mortgage.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.checkid
     *
     * @param checkid the value for mortgage.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setCheckid(Integer checkid) {
        this.checkid = checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgagemoney
     *
     * @return the value of mortgage.mortgagemoney
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public BigDecimal getMortgagemoney() {
        return mortgagemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgagemoney
     *
     * @param mortgagemoney the value for mortgage.mortgagemoney
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgagemoney(BigDecimal mortgagemoney) {
        this.mortgagemoney = mortgagemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgagescope
     *
     * @return the value of mortgage.mortgagescope
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getMortgagescope() {
        return mortgagescope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgagescope
     *
     * @param mortgagescope the value for mortgage.mortgagescope
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgagescope(String mortgagescope) {
        this.mortgagescope = mortgagescope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgagestart
     *
     * @return the value of mortgage.mortgagestart
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Date getMortgagestart() {
        return mortgagestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgagestart
     *
     * @param mortgagestart the value for mortgage.mortgagestart
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgagestart(Date mortgagestart) {
        this.mortgagestart = mortgagestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgageend
     *
     * @return the value of mortgage.mortgageend
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Date getMortgageend() {
        return mortgageend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgageend
     *
     * @param mortgageend the value for mortgage.mortgageend
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgageend(Date mortgageend) {
        this.mortgageend = mortgageend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgage.mortgagecode
     *
     * @return the value of mortgage.mortgagecode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getMortgagecode() {
        return mortgagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgage.mortgagecode
     *
     * @param mortgagecode the value for mortgage.mortgagecode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setMortgagecode(String mortgagecode) {
        this.mortgagecode = mortgagecode;
    }
}