package com.woniu.housemanager.pojo;

public class MortgagesLogout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.mlid
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private Integer mlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.mortgagecode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private String mortgagecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.mlname
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private String mlname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.mlcard
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private String mlcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.reason
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mortgageslogout.propertyrightcode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    private String propertyrightcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.mlid
     *
     * @return the value of mortgageslogout.mlid
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public Integer getMlid() {
        return mlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.mlid
     *
     * @param mlid the value for mortgageslogout.mlid
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setMlid(Integer mlid) {
        this.mlid = mlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.mortgagecode
     *
     * @return the value of mortgageslogout.mortgagecode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public String getMortgagecode() {
        return mortgagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.mortgagecode
     *
     * @param mortgagecode the value for mortgageslogout.mortgagecode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setMortgagecode(String mortgagecode) {
        this.mortgagecode = mortgagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.mlname
     *
     * @return the value of mortgageslogout.mlname
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public String getMlname() {
        return mlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.mlname
     *
     * @param mlname the value for mortgageslogout.mlname
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setMlname(String mlname) {
        this.mlname = mlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.mlcard
     *
     * @return the value of mortgageslogout.mlcard
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public String getMlcard() {
        return mlcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.mlcard
     *
     * @param mlcard the value for mortgageslogout.mlcard
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setMlcard(String mlcard) {
        this.mlcard = mlcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.reason
     *
     * @return the value of mortgageslogout.reason
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.reason
     *
     * @param reason the value for mortgageslogout.reason
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mortgageslogout.propertyrightcode
     *
     * @return the value of mortgageslogout.propertyrightcode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public String getPropertyrightcode() {
        return propertyrightcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mortgageslogout.propertyrightcode
     *
     * @param propertyrightcode the value for mortgageslogout.propertyrightcode
     *
     * @mbggenerated Wed Jun 17 17:42:30 CST 2020
     */
    public void setPropertyrightcode(String propertyrightcode) {
        this.propertyrightcode = propertyrightcode;
    }
}