package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class PlanPurpose implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planpurpose.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer purposeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planpurpose.purposename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String purposename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planpurpose.purposeid
     *
     * @return the value of planpurpose.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getPurposeid() {
        return purposeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planpurpose.purposeid
     *
     * @param purposeid the value for planpurpose.purposeid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setPurposeid(Integer purposeid) {
        this.purposeid = purposeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planpurpose.purposename
     *
     * @return the value of planpurpose.purposename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getPurposename() {
        return purposename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planpurpose.purposename
     *
     * @param purposename the value for planpurpose.purposename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setPurposename(String purposename) {
        this.purposename = purposename;
    }
}