package com.woniu.housemanager.pojo;

public class PresalePermit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presalepermit.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer pspid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presalepermit.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer bdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presalepermit.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presalepermit.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer checkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column presalepermit.presalepermitcode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String presalepermitcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presalepermit.pspid
     *
     * @return the value of presalepermit.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getPspid() {
        return pspid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presalepermit.pspid
     *
     * @param pspid the value for presalepermit.pspid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setPspid(Integer pspid) {
        this.pspid = pspid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presalepermit.bdid
     *
     * @return the value of presalepermit.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getBdid() {
        return bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presalepermit.bdid
     *
     * @param bdid the value for presalepermit.bdid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setBdid(Integer bdid) {
        this.bdid = bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presalepermit.buildingid
     *
     * @return the value of presalepermit.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presalepermit.buildingid
     *
     * @param buildingid the value for presalepermit.buildingid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presalepermit.checkid
     *
     * @return the value of presalepermit.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presalepermit.checkid
     *
     * @param checkid the value for presalepermit.checkid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setCheckid(Integer checkid) {
        this.checkid = checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column presalepermit.presalepermitcode
     *
     * @return the value of presalepermit.presalepermitcode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getPresalepermitcode() {
        return presalepermitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column presalepermit.presalepermitcode
     *
     * @param presalepermitcode the value for presalepermit.presalepermitcode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setPresalepermitcode(String presalepermitcode) {
        this.presalepermitcode = presalepermitcode;
    }
}