package com.woniu.housemanager.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Register implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.registercode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String registercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.bsid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String bsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.registerdate
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date registerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.qiudihao
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String qiudihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String houseaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.commonpeople
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String commonpeople;

    private WorkerInfo workerInfo;

    private Bussnessstatus bussnessstatus;

    public WorkerInfo getWorkerInfo() {
        return workerInfo;
    }

    public void setWorkerInfo(WorkerInfo workerInfo) {
        this.workerInfo = workerInfo;
    }

    public Bussnessstatus getBussnessstatus() {
        return bussnessstatus;
    }

    public void setBussnessstatus(Bussnessstatus bussnessstatus) {
        this.bussnessstatus = bussnessstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.registercode
     *
     * @return the value of register.registercode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getRegistercode() {
        return registercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.registercode
     *
     * @param registercode the value for register.registercode
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setRegistercode(String registercode) {
        this.registercode = registercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.workid
     *
     * @return the value of register.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.workid
     *
     * @param workid the value for register.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.bsid
     *
     * @return the value of register.bsid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getBsid() {
        return bsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.bsid
     *
     * @param bsid the value for register.bsid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setBsid(String bsid) {
        this.bsid = bsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.registerdate
     *
     * @return the value of register.registerdate
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.registerdate
     *
     * @param registerdate the value for register.registerdate
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.qiudihao
     *
     * @return the value of register.qiudihao
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getQiudihao() {
        return qiudihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.qiudihao
     *
     * @param qiudihao the value for register.qiudihao
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setQiudihao(String qiudihao) {
        this.qiudihao = qiudihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.houseaddress
     *
     * @return the value of register.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getHouseaddress() {
        return houseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.houseaddress
     *
     * @param houseaddress the value for register.houseaddress
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setHouseaddress(String houseaddress) {
        this.houseaddress = houseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.commonpeople
     *
     * @return the value of register.commonpeople
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getCommonpeople() {
        return commonpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.commonpeople
     *
     * @param commonpeople the value for register.commonpeople
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setCommonpeople(String commonpeople) {
        this.commonpeople = commonpeople;
    }
}