package com.woniu.housemanager.pojo;

public class RoleTree extends RoleTreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.rule
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String rule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.rule
     *
     * @return the value of roletree.rule
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.rule
     *
     * @param rule the value for roletree.rule
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setRule(String rule) {
        this.rule = rule;
    }
}