package com.woniu.housemanager.pojo;

import java.io.Serializable;

public class Structrue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structrue.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer structureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structrue.structurename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String structurename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structrue.structureid
     *
     * @return the value of structrue.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getStructureid() {
        return structureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structrue.structureid
     *
     * @param structureid the value for structrue.structureid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setStructureid(Integer structureid) {
        this.structureid = structureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structrue.structurename
     *
     * @return the value of structrue.structurename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getStructurename() {
        return structurename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structrue.structurename
     *
     * @param structurename the value for structrue.structurename
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setStructurename(String structurename) {
        this.structurename = structurename;
    }
}