package com.woniu.housemanager.pojo;

public class WorkerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.uid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.workname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String workname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.worksex
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Boolean worksex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.workage
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private Integer workage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.workschool
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String workschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.worklevel
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String worklevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workerinfo.workphone
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    private String workphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.workid
     *
     * @return the value of workerinfo.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.workid
     *
     * @param workid the value for workerinfo.workid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.uid
     *
     * @return the value of workerinfo.uid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.uid
     *
     * @param uid the value for workerinfo.uid
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.workname
     *
     * @return the value of workerinfo.workname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getWorkname() {
        return workname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.workname
     *
     * @param workname the value for workerinfo.workname
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkname(String workname) {
        this.workname = workname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.worksex
     *
     * @return the value of workerinfo.worksex
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Boolean getWorksex() {
        return worksex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.worksex
     *
     * @param worksex the value for workerinfo.worksex
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorksex(Boolean worksex) {
        this.worksex = worksex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.workage
     *
     * @return the value of workerinfo.workage
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public Integer getWorkage() {
        return workage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.workage
     *
     * @param workage the value for workerinfo.workage
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkage(Integer workage) {
        this.workage = workage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.workschool
     *
     * @return the value of workerinfo.workschool
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getWorkschool() {
        return workschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.workschool
     *
     * @param workschool the value for workerinfo.workschool
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkschool(String workschool) {
        this.workschool = workschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.worklevel
     *
     * @return the value of workerinfo.worklevel
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getWorklevel() {
        return worklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.worklevel
     *
     * @param worklevel the value for workerinfo.worklevel
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorklevel(String worklevel) {
        this.worklevel = worklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workerinfo.workphone
     *
     * @return the value of workerinfo.workphone
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public String getWorkphone() {
        return workphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workerinfo.workphone
     *
     * @param workphone the value for workerinfo.workphone
     *
     * @mbggenerated Sun Jun 07 17:07:39 CST 2020
     */
    public void setWorkphone(String workphone) {
        this.workphone = workphone;
    }
}